image:
- Visual Studio 2015

version: 0.1.{build}

platform:
  - x64

build:
  parallel: true                  # enable MSBuild parallel builds
  project: QuantLib.sln           # path to Visual Studio solution or project

build_script:
  - cmd: mkdir build
  - cmd: cd build
  - cmd: cmake -DBUILD_TEST=ON .. -G "Visual Studio 14 2015 Win64"
  - cmd: cmake --build . --config Release

test_script:
  - cmd: cd bin

environment:
  BOOST_INCLUDEDIR: C:\Libraries\boost_1_63_0
